source "https://rubygems.org"

ruby "3.3.3"

gem "rails", "~> 8.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors", "~> 2.0"
gem "bootsnap", "~> 1.18", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rspec-rails", "~> 7.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "shoulda-matchers", "~> 6.4"
  gem "faker", "~> 3.5"
end

group :development do
  gem "listen", "~> 3.9"
end
